### ISSUE TITLE
[RFE] support autocompletion in the initial input box

### ISSUE THREAD

**Issue by TomasTomecek** [release-engineering/estuary#30]
...and please complete even on 0 characters entered: that would actually solve #29 for me. Especially when the completion list would be sorted by date.

**Comment by mprahl** [comment]
Good suggestion @TomasTomecek. We were planning to do this at the end of Q2 or at the beginning of Q3 since it wasn't deemed a priority. If you disagree, I'll gladly prioritize this.

**Comment by TomasTomecek** [comment]
That's just fine, thanks!

**Comment by mprahl** [comment]
I don't think we'll ever go to this since Estuary's plan were scaled back significantly last year. I'll close this to keep the backlog clean.
