### ISSUE TITLE
Unable to list all builds initiated by a specific freshmaker event

### ISSUE THREAD

**Issue by TomasTomecek** [release-engineering/estuary#35]
When I look at the visualization, I can see there is a freshmaker event 1872. There are two lines coming from the event: a line to a specific image and a line described as "36 more". I would like to see what those other 36 are.

A solution for me could be to see the list as details of a specific freshmkaer event. E.g.
```
Triggered Container Builds Count   37
Triggered Container Builds         rh-nodejs...
                                   rh-python...
```

**Comment by mprahl** [comment]
@TomasTomecek, we're going to implement a table-view that lists all the container builds when you click on "36 more". It's on the road-map for next sprint.

You can follow progress on this on FACTORY-2367.

**Comment by TomasTomecek** [comment]
nice!

**Comment by mprahl** [comment]
This has been deployed to production.
